name: Build container image on microservice release

on:
  push:
    tags:
      - '**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse tag & set IMAGE_NAME and TAG environment variables
        run: |
          MICROSERVICE=${GITHUB_REF##*/}
          MICROSERVICE=${MICROSERVICE%@*}
          echo "MICROSERVICE=${MICROSERVICE}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/microservice-${{ env.MICROSERVICE }}
          tags: |
            type=match,pattern=[^@]+@v(\d+),group=1
            type=match,pattern=[^@]+@v(\d+\.\d+),group=1
            type=match,pattern=[^@]+@v(.*),group=1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.MICROSERVICE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
